### ISSUE TITLE
UnicodeDecodeError when running setup.py

### ISSUE THREAD

**Issue by danschef** [andrewekhalel/sewar#12]
Running setup.py may raise a UnicodeDecodeError on some systems:

```
$ pip install sewar
Collecting sewar
  Downloading https://files.pythonhosted.org/packages/0c/5e/9153f0867d94c2c6959c35fda5a323cf3ca8e9979d03426f8444a4b3ba5b/sewar-0.4.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/gfz-fe/python_GFZ/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ljfrpcw9/sewar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ljfrpcw9/sewar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ljfrpcw9/sewar/pip-egg-info
         cwd: /tmp/pip-install-ljfrpcw9/sewar/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ljfrpcw9/sewar/setup.py", line 12, in <module>
        long_description=readme(),
      File "/tmp/pip-install-ljfrpcw9/sewar/setup.py", line 6, in readme
        return f.read()
      File "~/python/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 722: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
To avoid this, just replace [this line](https://github.com/andrewekhalel/sewar/blob/d7d30c5e7e2852ea7fadd1fa8f7144a5f5467361/setup.py#L5) by `with open('README.md', encoding='UTF-8') as f:`.

**Comment by andrewekhalel** [comment]
Hi @danschef,

Thanks for figuring this out. Fixed with commit e7a87402ed0fc71844322f0dfa1fcfe8117a89f3.

Best,
Andrew
