### ISSUE TITLE
from scipy.misc import imresize error

### ISSUE THREAD

**Issue by zhouhang95** [andrewekhalel/sewar#8]
F:\paj\neox_tools\hero2>sewar ssim 00080265.png 00325768.png
Traceback (most recent call last):
  File "c:\users\zhouhang\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zhouhang\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhouhang\Miniconda3\Scripts\sewar.exe\__main__.py", line 5, in <module>
  File "c:\users\zhouhang\miniconda3\lib\site-packages\sewar\__init__.py", line 18, in <module>
    from .no_ref import d_lambda
  File "c:\users\zhouhang\miniconda3\lib\site-packages\sewar\no_ref.py", line 5, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize'

**Comment by Anti-Alpha** [comment]
Same

**Comment by andrewekhalel** [comment]
Hi @zhouhang95,

Thanks for reporting this. Which version of scipy are you using?
You can try the below command to get scipy 1.1.0 which works for me
`pip3 install scipy==1.1.0`

**Comment by zhouhang95** [comment]
1.3.1

**Comment by andrewekhalel** [comment]
Since scipy 1.3.0rc1 resize has been [removed](https://github.com/scipy/scipy/releases/tag/v1.3.0rc1).

**Comment by harishkhollam** [comment]
Error even after using `pip3 install scipy==1.1.0`

**Comment by andrewekhalel** [comment]
Do you have Pillow installed?

`pip3 install pillow`

**Comment by zhouhang95** [comment]
Could you try to use anaconda/miniconda to find the problem. Anaconda is a good python enviroment manager.

**Comment by andrewekhalel** [comment]
Hi @zhouhang95,

Would you please try to the new version (0.4.3) and check if the error is resolved?
`pip3 install -U sewar`
